### PR TITLE
Add link to robotframework-requests library under external libraries

### PR DESCRIPTION
**Pull request by vkosuri**
https://github.com/bulkan/robotframework-requests/issues/87

### CODE REVIEW

**Comment by Tattoo** [comment]
Isn't this library already there as "HTTP Library (requests)"?

**Comment by vkosuri** [comment]
HTTP Libaray based on [livetest](https://pypi.python.org/pypi/livetest) and robotframework-requests based on [requests](https://github.com/kennethreitz/requests)

**Comment by Tattoo** [comment]
Yes, isn't the latter already the one you have now added in this pull request? In other words: the library is already there, isn't it?

**Comment by vkosuri** [comment]
Yes i think so

**Comment by Tattoo** [comment]
I'll close this PR as the library is already listed on the web page

**Pull request closed without merging**
