### PR TITLE
Updated Robotmk description and URL

### PR DESCRIPTION
**Pull request by simonmeggle**
I updated the repo URL and wrote a more comprehensive description of the project.

### CODE REVIEW

**Comment by Snooz82** [comment]
@simonmeggle Can you please rebase and make your changes based on that.
Maybe that fixes the issues.

**Comment by simonmeggle** [comment]
> @simonmeggle Can you please rebase and make your changes based on that. Maybe that fixes the issues.

Thanks, done!

**Comment by simonmeggle** [comment]
Are there any news on that? I rebased but that did not fix the error.

**Comment by samipe** [comment]
Merged, thanks! Sorry for not noticing this earlier.

**Pull request merged**
