### PR TITLE
Add "ExcelDataDriver" library into external library

### PR DESCRIPTION
**Pull request by atthaboon**
Hi,
I kindly ask to add "ExcelDataDriver" as a external library.

Name: ExcelDataDriver
Short description: ExcelDataDriver is a Excel Data-Driven Testing library for RobotFramework.
Link: https://github.com/qahive/robotframework-ExcelDataDriver

Regards,
Atthaboon Sanurt

### CODE REVIEW

**Comment by samipe** [comment]
Hello,
Thank you for contribution. Can you please remove all other changes apart from those made to App.vue - I'll build it after merge.

**Comment by atthaboon** [comment]
> Hello,
> Thank you for contribution. Can you please remove all other changes apart from those made to App.vue - I'll build it after merge.

Thanks a lot.  I already reverse all the change except App.vue.

**Comment by atthaboon** [comment]
> Hello,
> Thank you for contribution. Can you please remove all other changes apart from those made to App.vue - I'll build it after merge.

Already apply based on comment could you help to recheck.

**Comment by pekkaklarck** [comment]
How is this tool different compared to the original DataDriver by @Snooz82? That should be documented in the project pages better and then we can decide should we add it to robotframework.org or not.

**Pull request closed without merging**
