### PR TITLE
Add NRL user

### PR DESCRIPTION
**Pull request by guleyupo**
And alphabetize user list.

### CODE REVIEW

**Comment by pekkaklarck** [comment]
Also, does SAGE you added too belong under libraries or rather under tools? Link pointing to more Robot related information would be nice as well.

And yeah, NRL is a great addition under users. Thanks!

**Comment by guleyupo** [comment]
If not strictly alphabetical, where should new additions go. Because last two entries are in a div of their own, any addition to the three columns will make the list look ugly. I understand you want to see a simple diff between versions but Steeri and Zilogic has to move to add a new entry to one of the columns above.

**Comment by guleyupo** [comment]
Ok, you can check it out again.

**Comment by pekkaklarck** [comment]
Cool, thanks! I'll let @Tattoo to do the final review, possible tuning to formatting, merging.

**Comment by guleyupo** [comment]
I'd like to mark this done on my todo list. It is a very simple change; can you accept, deny or suggest changes please?

**Comment by Tattoo** [comment]
Hi @guleyupo ,

Sorry to have kept you waiting.

I moved the link in Tools > Other to a different column so it looks a bit better. I also resized the logo in Users section as well to fit with the rest. If these are not fine or you want to change them in the future, please put down a issue or pull request.

Thank you for contributing and have a nice year 2018!

**Pull request merged**
